version: '3.9'

services:
  api1:
    image: ricardomauro/rinha-2024q1-dotnet:latest
    container_name: rinhaapi1
    network_mode: host
    environment: 
      ConnectionStrings__Default: Server=127.0.0.1;Database=rinha;Uid=root;Pwd=password.123;
      DOTNET_URLS: http://*:9997
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      db:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '80MB'

  api2:
    image: ricardomauro/rinha-2024q1-dotnet:latest
    container_name: rinhaapi2
    network_mode: host
    environment: 
      ConnectionStrings__Default: Server=127.0.0.1;Database=rinha;Uid=root;Pwd=password.123;
      DOTNET_URLS: http://*:9998
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      db:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '80MB'

  envoy:
    image: envoyproxy/envoy:v1.29-latest
    container_name: rinhaproxy
    network_mode: host
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '134MB'

  db:
    image: mysql:latest
    container_name: rinhadb
    network_mode: host
    command: --log_error_verbosity=2 --skip-log-bin
    volumes:
      - ./mysql/dump:/docker-entrypoint-initdb.d
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password.123
      MYSQL_DATABASE: rinha
      MYSQL_USER: rinha
      MYSQL_PASSWORD: password.123
      MYSQL_ALLOW_EMPTY_PASSWORD: yes

    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 15s
      timeout: 5s
      retries: 10

    ulimits:
      nofile:
        soft: 20000
        hard: 40000

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '256MB'
