version: '3.9'

services:
  api1:
    build:
      context: RinhaBackend2024Q1/.
      dockerfile: Dockerfile
    container_name: rinhaapi1
    network_mode: host
    environment: 
      ConnectionStrings__Default: Server=127.0.0.1;Database=rinha;Uid=root;Pwd=password.123;
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: https://+:9997;http://+:8097
      ASPNETCORE_Kestrel__Certificates__Default__Password: password.123
      ASPNETCORE_Kestrel__Certificates__Default__Path: /app/https/aspnetapp.pfx
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '80MB'

  db:
    image: mariadb:lts-jammy
    container_name: rdb
    network_mode: host
    command: --skip-log-bin
    volumes:
      - ./mysql/dump/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./mysql/my.cnf:/etc/mysql/my.cnf:ro
    tmpfs:
      - /var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_USER: root
      MARIADB_ROOT_PASSWORD: password.123
      MARIADB_DATABASE: rinha
      MARIADB_USER: rinha
      MARIADB_PASSWORD: password.123
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1

    healthcheck:
      test: 
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

    ulimits:
      nofile:
        soft: 65535
        hard: 65535

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '256MB'

          
  phpmyadmin:
    depends_on:
      - db
    network_mode: host
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: 127.0.0.1
      MYSQL_ROOT_PASSWORD: password.123