version: '3.9'

services:
  api1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: r-api_pg-1
    network_mode: host
    volumes:
      - sock_vol:/tmp/:rw
    environment: 
      ConnectionStrings__Default: Server=127.0.0.1;Database=rinha;Uid=root;Pwd=password.123;
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8098
      SOCKET_ADDRESS: /tmp/kestrel-api1.sock
      TRAIL: P_1
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '80MB'

  api2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: r-api_pg-2
    network_mode: host
    volumes:
      - sock_vol:/tmp/:rw
    environment: 
      ConnectionStrings__Default: Server=127.0.0.1;Database=rinha;Uid=root;Pwd=password.123;
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8097
      SOCKET_ADDRESS: /tmp/kestrel-api2.sock
      TRAIL: P_2
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '80MB'

  yarp:
    image: ricardomauro/rinha-2024q1-dotnet-yarp:latest
    container_name: rpy-proxy
    network_mode: host
    environment: 
      DOTNET_URLS: http://*:9999
      ASPNETCORE_ENVIRONMENT: Production
    volumes:
      - ./yarp/secrets.json:/app/secrets.json:ro
      - sock_vol:/tmp/:rw
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '134MB'

  db:
    image: postgres:16.2
    container_name: r-pg
    network_mode: host
    command: 'postgres -c max_connections=300 -c shared_buffers=96MB -c checkpoint_timeout=600 -c synchronous_commit=off -c fsync=off -c full_page_writes=off -c work_mem=16MB'
    hostname: db
    environment:
      - POSTGRES_PASSWORD=rinha
      - POSTGRES_USER=rinha
      - POSTGRES_DB=rinha
    volumes:
      - ./sql/ddl-postgresql.sql:/docker-entrypoint-initdb.d/ddl-postgresql.sql:ro
      - type: tmpfs
        target: /var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '256MB'

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    network_mode: host
    environment:
      PGADMIN_DEFAULT_EMAIL: radmin@email.com
      PGADMIN_DEFAULT_PASSWORD: password.123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    restart: unless-stopped

volumes:
  sock_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs