version: '3.9'

services:
  api1:
    build:
      context: RinhaBackend2024Q1/.
      dockerfile: Dockerfile
    container_name: rinhaapi1
    network_mode: host
    environment: 
      ConnectionStrings__Default: Server=127.0.0.1;Database=rinha;Uid=root;Pwd=password.123;
      DOTNET_URLS: http://*:9997
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      db:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '80MB'

  api2:
    build:
      context: RinhaBackend2024Q1/.
      dockerfile: Dockerfile
    container_name: rinhaapi2
    network_mode: host
    environment: 
      ConnectionStrings__Default: Server=127.0.0.1;Database=rinha;Uid=root;Pwd=password.123;
      DOTNET_URLS: http://*:9998
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      db:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '80MB'

  envoy:
    image: envoyproxy/envoy:v1.29-latest
    container_name: rinhaproxy
    network_mode: host
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '134MB'

  db:
    image: mysql:latest
    container_name: rinhadb
    network_mode: host
    #volumes:
    #  - db_data:/var/lib/mysql
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password.123
      MYSQL_DATABASE: rinha
      MYSQL_USER: rinha
      MYSQL_PASSWORD: password.123

    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 15s
      timeout: 5s
      retries: 10

  phpmyadmin:
    depends_on:
      - db
    network_mode: host
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: 127.0.0.1
      MYSQL_ROOT_PASSWORD: password.123