version: '3.9'

services:
  db:
    image: postgres:16.2
    container_name: rinhadb
    network_mode: host
    command: 'postgres -c max_connections=300 -c shared_buffers=96MB -c checkpoint_timeout=600 -c synchronous_commit=off -c fsync=off -c full_page_writes=off -c work_mem=16MB'
    hostname: db
    environment:
      - POSTGRES_PASSWORD=rinha
      - POSTGRES_USER=rinha
      - POSTGRES_DB=rinha
    volumes:
      - ./sql/ddl-postgresql.sql:/docker-entrypoint-initdb.d/01-ddl.sql:ro
      - type: tmpfs
        target: /var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '256MB'
    healthcheck:
      test: ["CMD", "pg_isready", "--username", "rinha"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 15s
      # start_interval: 1s # only available in Docker engine 25+

  pgadmin:
    container_name: rinhadb_admin
    image: dpage/pgadmin4
    network_mode: host
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: radmin@email.com
      PGADMIN_DEFAULT_PASSWORD: password.123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    restart: unless-stopped