GET https://localhost:7272/clientes/1/extrato


###

POST https://localhost:7272/clientes/1/transacoes
Content-Type: application/json

{
    "valor": 400,
    "tipo" : "c",
    "descricao" : "descricao"
}