###


GET http://localhost:9999/clientes/1/extrato


###

POST http://localhost:9999/clientes/1/transacoes
Content-Type: application/json

{
    "valor": 400,
    "tipo" : "d",
    "descricao" : "descricao"
}